---
- name: Update client packages
  hosts: passkey-client
  vars_files:
    - variables.yml

  tasks:
    - name: Enable testing repo
      community.general.copr:
        host: copr.fedorainfracloud.org
        state: enabled
        name: ipedrosa/passkey-auth
    
    - name: Update packages
      ansible.builtin.dnf:
        name: sssd,sssd-common,sssd-passkey,fido2-tools,yubikey-manager,umockdev,gcc,openssl,openssl-devel,freeipa-client
        state: latest

    - name: Clone Scott's notes
      ansible.builtin.git:
        repo: https://gitlab.cee.redhat.com/idm-qe/sssd-passkey-tests
        dest: /root/sssd-passkey-tests
      environment:
        - GIT_SSL_NO_VERIFY: "true"

    - name: Build mocks
      shell: "cd /root/sssd-passkey-tests && gcc -fPIC -shared -o random.so random.c -lcrypto"

    - name: Move random.so
      ansible.builtin.copy:
        remote_src: true
        src: /root/sssd-passkey-tests/random.so
        dest: /opt/random.so
        owner: root
        group: root
        mode: '0755'

- name: Update IPA packages
  hosts: passkey-ipa
  vars_files:
    - variables.yml

  tasks:
    - name: Enable testing repo
      community.general.copr:
        host: copr.fedorainfracloud.org
        state: enabled
        name: ipedrosa/passkey-auth
    
    - name: Update packages
      ansible.builtin.dnf:
        name: freeipa-server,freeipa-client,sssd,sssd-common,sssd-passkey,umockdev,gcc,openssl,openssl-devel
        state: latest

    - name: Clone Scott's notes
      ansible.builtin.git:
        repo: https://gitlab.cee.redhat.com/idm-qe/sssd-passkey-tests
        dest: /root/sssd-passkey-tests
      environment:
        - GIT_SSL_NO_VERIFY: "true"

    - name: Build mocks
      shell: "cd /root/sssd-passkey-tests && gcc -fPIC -shared -o random.so random.c -lcrypto"

    - name: Move random.so
      ansible.builtin.copy:
        remote_src: true
        src: /root/sssd-passkey-tests/random.so
        dest: /opt/random.so
        owner: root
        group: root
        mode: '0755'
