---
- name: Update client packages
  hosts: passkey-client
  vars_files:
    - variables.yml

  tasks:
    - name: Enable testing repo
      community.general.copr:
        host: copr.fedorainfracloud.org
        state: enabled
        name: ipedrosa/passkey-auth
    
    - name: Update packages
      ansible.builtin.dnf:
        name: sssd,sssd-common,sssd-passkey,fido2-tools,yubikey-manager,umockdev,gcc,openssl,openssl-devel
        state: latest

    - name: Clone Scott's notes
      ansible.builtin.git:
        repo: https://gitlab.cee.redhat.com/spoore/sc-notes/
        dest: /root/data
      environment:
        - GIT_SSL_NO_VERIFY: "true"

    - name: Build mocks
      shell: "cd /root/data/fido2 && gcc -fPIC -shared -o random.so random.c -lcrypto"

- name: Update IPA packages
  hosts: passkey-ipa
  vars_files:
    - variables.yml

  tasks:
    - name: Enable testing repo
      community.general.copr:
        host: copr.fedorainfracloud.org
        state: enabled
        name: ipedrosa/passkey-auth
    
    - name: Update packages
      ansible.builtin.dnf:
        name: freeipa-server,freeipa-client,sssd,sssd-common,sssd-passkey,umockdev,gcc,openssl,openssl-devel
        state: latest

    - name: Clone Scott's notes
      ansible.builtin.git:
        repo: https://gitlab.cee.redhat.com/spoore/sc-notes/
        dest: /root/data
      environment:
        - GIT_SSL_NO_VERIFY: "true"

    - name: Build mocks
      shell: "cd /root/data/fido2 && gcc -fPIC -shared -o random.so random.c -lcrypto"
